# Generated by Django 4.2.3 on 2023-07-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="contact", name="email",),
        migrations.RemoveField(model_name="spamnumber", name="email",),
    ]
